In [1]:
import numpy as np

### Array types and conversions between types

In [3]:
integers=np.array([10,20,30,40,50])
integers

array([10, 20, 30, 40, 50])

In [4]:
integers.dtype

dtype('int64')

In [5]:
smallerIntegers=np.array(integers,dtype=np.int8)
smallerIntegers

array([10, 20, 30, 40, 50], dtype=int8)

In [12]:
print(f'total bytes for "small integers" array: {smallerIntegers.nbytes}')
print(f'total bytes for "integers" array: {integers.nbytes}')

total bytes for "small integers" array: 5
total bytes for "integers" array: 40


In [13]:
# pay attention to overflow
overflow = np.array([127,128,129], dtype = np.int8)
overflow

OverflowError: Python integer 128 out of bounds for int8

In [16]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])
floats.dtype

dtype('float64')

### Multidimensional arrays

In [17]:
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
nums[0,4]

np.int64(5)

In [20]:
nums.ndim

2

In [26]:
# three dimensional
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
multi_arr.ndim

3

In [27]:
multi_arr[1,0,2]

np.int64(9)

### Creating arrays from Lists and other Python structures

In [31]:
first_list=[1,2,3,4,5,6,7,8,9,10]
first_array=np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
float_list=[1,2,3,-1.23,50,128000.56,4.56]
float_array=np.array(second_list)
float_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [34]:
float_array.dtype

dtype('float64')

In [36]:
# mixed datatype list gets converted to string array
mixed_type_list=['Ann',111111,'Peter',111112,'Susan',111113,'John',111114]
string_array=np.array(mixed_type_list)
string_array

array(['Ann', '111111', 'Peter', '111112', 'Susan', '111113', 'John',
       '111114'], dtype='<U21')

In [37]:
string_array.dtype

dtype('<U21')

In [38]:
first_tuple=(5, 10, 15, 20, 25, 30)
array_from_tuple=np.array(first_tuple)
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [39]:
multi_dim_list=[
    [
        [0,1,2], 
        [3,4,5]
    ], 
    [
        [6,7,8],
        [9,10,11]
    ]
] 
arr_from_multi_dim_list=np.array(multi_dim_list)
arr_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Intrisic NumPy array creation

In [40]:
integers_array=np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
integers_second_array=np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [42]:
# with step
integers_third_array=np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [45]:
# float array -> default 50 values
first_floats_arr=np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [46]:
# with 5 values
second_floats_arr=np.linspace(10,20,5)
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [47]:
first_rand_arr=np.random.rand(10)
first_rand_arr

array([0.96832675, 0.05289091, 0.2433892 , 0.39989715, 0.45058437,
       0.29876079, 0.9864917 , 0.38622959, 0.10094819, 0.68467519])

In [48]:
# wo dimentional
second_rand_arr=np.random.rand(4,4)
second_rand_arr

array([[0.70317825, 0.73684924, 0.98312481, 0.96606324],
       [0.28451607, 0.22476368, 0.69202132, 0.04302069],
       [0.77964428, 0.72996407, 0.10536848, 0.93583034],
       [0.15258916, 0.44920845, 0.81914706, 0.22913637]])

In [49]:
second_rand_arr.ndim

2

In [50]:
# random int array
third_rand_arr=np.random.randint(0,100,20)
third_rand_arr

array([99, 14, 31, 46,  9, 64, 17, 73, 45, 68, 50, 83, 39,  2, 67, 98, 77,
       60, 99, 75], dtype=int32)

In [53]:
# random int multi dimentional array
fourth_rand_arr=np.random.randint(0,10,size=(2,2))
fourth_rand_arr

array([[5, 6],
       [7, 0]], dtype=int32)

### Creating arrays filled with constant values

In [54]:
first_z_array=np.zeros(5)
first_z_array

array([0., 0., 0., 0., 0.])

In [55]:
second_z_array=np.zeros((4,5))
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
second_ones_array=np.ones((7,8))
second_ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
# int type array
third_ones_array=np.ones((4,5),dtype=int)
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [59]:
first_fill_array=np.empty(10,dtype=int)
first_fill_array.fill(12)
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [60]:
first_full_array=np.full(5,10)
first_full_array

array([10, 10, 10, 10, 10])

In [61]:
second_full_array=np.full((4,5),8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

###  Finding the shape and size of an array

In [62]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
np.shape(first_arr)

(20,)

In [65]:
second_arr=np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [66]:
np.shape(second_arr)

(10, 2)

In [67]:
np.size(second_arr)

20

In [68]:
np.size(second_arr,1)

2

In [69]:
np.size(second_arr,0)

10

In [78]:
third_arr=np.full((2,3,4),10)
third_arr

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [79]:
np.size(third_arr,0)

2

In [80]:
np.size(third_arr,1)

3

In [81]:
np.size(third_arr,2)

4

In [82]:
np.size(third_arr)

24

### Adding, removing and sorting elements

In [83]:
first_arr=np.array([1, 2, 3, 5])
first_arr

array([1, 2, 3, 5])

In [88]:
new_first_arr=np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [90]:
new_second_arr=np.append(first_arr,8)
new_second_arr

array([1, 2, 3, 5, 8])

In [92]:
del_arr=np.delete(first_arr,3)
del_arr

array([1, 2, 3])

In [93]:
integers_arr=np.random.randint(0,20,20)
integers_arr

array([ 2,  8,  1,  2, 18,  4, 10, 11,  7,  5, 11,  7,  6, 14, 14, 17, 17,
        6, 14, 10], dtype=int32)

In [94]:
print(np.sort(integers_arr))

[ 1  2  2  4  5  6  6  7  7  8 10 10 11 11 14 14 14 17 17 18]


In [95]:
integers_2dim_arr=np.array([[3, 2, 5,7, 4], [5, 0, 8,3, 1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [96]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [97]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
colors

array(['orange', 'green', 'yellow', 'white', 'black', 'pink', 'blue',
       'red'], dtype='<U6')

In [98]:
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']


### Copies and views

In [99]:
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [102]:
# same Id -> same object
students_ids_number_reg=students_ids_number
print(f'id of students_ids_number {id(students_ids_number)}')
print(f'id of students_ids_number_reg {id(students_ids_number_reg)}')

id of students_ids_number 2471772304944
id of students_ids_number_reg 2471772304944


In [103]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [104]:
# make a copy
students_ids_number_cp=students_ids_number.copy()

In [105]:
print(students_ids_number_cp==students_ids_number)

[ True  True  True  True  True  True  True  True]


In [108]:
students_ids_number[0]=1000
print (f'original: {students_ids_number}')
print(f'copy: {students_ids_number_cp}')

original: [1000 2222 1313 1414 1515 1616 1717 1818]
copy: [1111 2222 1313 1414 1515 1616 1717 1818]


### Reshaping arrays

In [109]:
first_arr=np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [110]:
second_arr=np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
third_arr=np.reshape(first_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [113]:
# this will fail as reshpae cannot be done with size of 12 entries
fourth_arr=np.reshape(first_arr,(4,4))

ValueError: cannot reshape array of size 12 into shape (4,4)

In [114]:
sixth_arr=np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
# flatten an array with reshape
seventh_arr_flat=np.reshape(sixth_arr,-1)
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [116]:
# flatten an array 

eighth_arr_flat=sixth_arr.flatten()
print(f'eighth_arr_flat:{eighth_arr_flat}')

ninth_arr_rav=sixth_arr.ravel()
print(f'ninth_arr_rav:",{ninth_arr_rav}')

eighth_arr_flat:[1 2 3 4 5 6]
ninth_arr_rav:",[1 2 3 4 5 6]


### Indexing and slicing

In [117]:
twodim_arr=np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
twodim_arr[1,1]

np.int64(5)

In [119]:
twodim_arr[1]

array([4, 5, 6, 7])

In [123]:
threedim_arr=np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [124]:
threedim_arr[2,-1,-1]

np.int64(59)

In [125]:
onedim_arr=np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [127]:
onedim_arr[-3:]

array([7, 8, 9])

In [128]:
# step 2
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [129]:
twodim_arr[1,:]

array([4, 5, 6, 7])

### Joining and splitting ararys

In [131]:
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)

print(f'first_arr {first_arr}')
print(f'second_arr" {second_arr}'     )

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr" [11 12 13 14 15 16 17 18 19 20]


In [132]:
con_arr=np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [133]:
third_2darr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
third_2darr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [134]:
fourth_2darr=np.array([[11,12,13,14,15], [16,17,18,19,20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [135]:
con2d_arr = np.concatenate((third_2darr,fourth_2darr),axis=1)
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [138]:
con2d_arr_axis_1 = np.concatenate((third_2darr,fourth_2darr),axis=0)
con2d_arr_axis_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [139]:
st_arr = np.stack((first_arr,second_arr))
st_arr 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [142]:
hst_arr=np.hstack((first_arr,second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [143]:
vst_arr=np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [144]:
fifth_arr=np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [145]:
sp_arr=np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [146]:
sp_arr=np.array_split(fifth_arr,8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

### Arithmetic operations

In [148]:
a=np.arange(1,11)
b=np.arange(21,31)
print(f'a {a}')
print(f'b {b}')

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [149]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [150]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [151]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [152]:
c=np.arange(2,12)
print(f'c {c}')

c [ 2  3  4  5  6  7  8  9 10 11]


In [153]:
a**c

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [154]:
# you can use method as well  multiply, add, subtract etc
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

### Brodcasting

In [155]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
b=np.arange(1,4)
b

array([1, 2, 3])

In [157]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [158]:
c=np.arange(1,3)
c

array([1, 2])

In [159]:
# this will fail due to incompatible shape
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [160]:
d=np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [161]:
e=np.arange(4)
e

array([0, 1, 2, 3])

In [162]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

### Aggregate functions

In [163]:
first_arr=np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [164]:
first_arr.sum()

np.int64(550)

In [165]:
second_arr=np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [166]:
second_arr.sum()

np.int64(450)

In [167]:
third_arr=np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [168]:
third_arr.sum()

np.int64(550)

In [169]:
second_arr.sum(axis=0)

array([120, 150, 180])

In [170]:
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [171]:
first_arr.prod()

np.int64(36288000000000000)

In [172]:
second_arr.prod()

np.int64(362880000000000)

In [173]:
np.average(third_arr)

np.float64(55.0)

In [174]:
np.mean(first_arr)

np.float64(55.0)

### How to get unique items and counts

In [175]:
first_arr=np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [176]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [177]:
second_arr=np.array([[1, 1, 2,1] ,[ 3, 1, 2,1] , [1, 1, 2, 1], [ 7, 1, 1, 1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [178]:
#Returns the sorted unique elements of an array
np.unique(second_arr)

array([1, 2, 3, 7])

In [179]:
np.unique(second_arr,axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [180]:
np.unique(second_arr,axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

### Transpose

In [181]:
first_2dimarr=np.arange(12).reshape((3,4))
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [182]:
np.transpose(first_2dimarr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [183]:
second_2dimarr=np.arange(6).reshape(3,2)
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [184]:
np.transpose(second_2dimarr,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [185]:
np.transpose(second_2dimarr)

array([[0, 2, 4],
       [1, 3, 5]])

In [186]:
first_3dimarr=np.arange(24).reshape(2,3,4)
first_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [188]:
np.moveaxis(first_3dimarr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

### Reversing an array

In [189]:
arr_1dim=[10,1,9,2,8,3,7,4,6,5]
arr_1dim

[10, 1, 9, 2, 8, 3, 7, 4, 6, 5]

In [190]:
arr_1dim[::-1]

[5, 6, 4, 7, 3, 8, 2, 9, 1, 10]

In [191]:
np.flip(arr_1dim)

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [192]:
arr_2dim=np.arange(9).reshape(3,3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [193]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [194]:
arr_3dim=np.arange(24).reshape(2,3,4)
arr_3dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [196]:
np.flip(arr_3dim)

array([[[23, 22, 21, 20],
        [19, 18, 17, 16],
        [15, 14, 13, 12]],

       [[11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]]])

### Universal functions

In [198]:
numbers=np.arange(1,11)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [199]:
np.sin(numbers)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [200]:
np.log(numbers)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [201]:
# creating numpy array
integers = np.arange(1, 101)
print("integers     :", *integers)

# creating own function
def modulo(val):
  return (val % 10)

# adding into numpy
mod_10=np.frompyfunc(modulo, 1, 1)

# using function over numpy array
mod_integers=mod_10(integers)
print("mod_integers :", *mod_integers)

integers     : 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100
mod_integers : 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0


## Introducing strides

In [202]:
numbers = np.arange(10, dtype = np.int8)
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [203]:
numbers.strides

(1,)

In [204]:
numbers.shape = 2,5
numbers

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int8)

In [205]:
numbers.strides

(5, 1)

In [206]:
first_array = np.zeros((100000,)) 
first_array

array([0., 0., 0., ..., 0., 0., 0.])

In [207]:
second_array = np.zeros((100000 * 100, ))[::100] 
second_array 

array([0., 0., 0., ..., 0., 0., 0.])

In [208]:
first_array.strides

(8,)

In [209]:
second_array.strides

(800,)

In [210]:
%timeit first_array.sum()

37.9 μs ± 3.36 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [211]:
%timeit second_array.sum()

450 μs ± 6.43 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Structured arrays

In [212]:
student_records = np.array([('Lazaro','Oneal', '0526993', 2009, 2.33), ('Dorie','Salinas', '0710325', 2006, 2.26), ('Mathilde','Hooper', '0496813', 2000, 2.56),('Nell','Gomez', '0740631', 2003, 2.22),('Lachelle','Jordan', '0490888', 2003, 2.13),('Claud','Waller', '0922492', 2004, 3.60),('Bob','Steele', '0264843', 2002, 2.79),('Zelma','Welch', '0885463', 2007, 3.69)],
       dtype=[('name', (np.str_, 10)),('surname', (np.str_, 10)), ('id', (np.str_,7)),('graduation_year', np.int32), ('gpa', np.float64)])
student_records

array([('Lazaro', 'Oneal', '0526993', 2009, 2.33),
       ('Dorie', 'Salinas', '0710325', 2006, 2.26),
       ('Mathilde', 'Hooper', '0496813', 2000, 2.56),
       ('Nell', 'Gomez', '0740631', 2003, 2.22),
       ('Lachelle', 'Jordan', '0490888', 2003, 2.13),
       ('Claud', 'Waller', '0922492', 2004, 3.6 ),
       ('Bob', 'Steele', '0264843', 2002, 2.79),
       ('Zelma', 'Welch', '0885463', 2007, 3.69)],
      dtype=[('name', '<U10'), ('surname', '<U10'), ('id', '<U7'), ('graduation_year', '<i4'), ('gpa', '<f8')])

In [213]:
student_records[['id','graduation_year']]     

array([('0526993', 2009), ('0710325', 2006), ('0496813', 2000),
       ('0740631', 2003), ('0490888', 2003), ('0922492', 2004),
       ('0264843', 2002), ('0885463', 2007)],
      dtype={'names': ['id', 'graduation_year'], 'formats': ['<U7', '<i4'], 'offsets': [80, 108], 'itemsize': 120})

In [214]:
students_sorted_by_surname = np.sort(student_records, order='surname')
print('Students sorted according to the surname :\n', students_sorted_by_surname)

Students sorted according to the surname :
 [('Nell', 'Gomez', '0740631', 2003, 2.22)
 ('Mathilde', 'Hooper', '0496813', 2000, 2.56)
 ('Lachelle', 'Jordan', '0490888', 2003, 2.13)
 ('Lazaro', 'Oneal', '0526993', 2009, 2.33)
 ('Dorie', 'Salinas', '0710325', 2006, 2.26)
 ('Bob', 'Steele', '0264843', 2002, 2.79)
 ('Claud', 'Waller', '0922492', 2004, 3.6 )
 ('Zelma', 'Welch', '0885463', 2007, 3.69)]


## Dates and time in NumPy

In [215]:
np.datetime64('2022-03-01') 

np.datetime64('2022-03-01')

In [216]:
np.datetime64('2022-03') 

np.datetime64('2022-03')

In [217]:
print('Number of weekdays in 2022:')
print(np.busday_count('2022','2023'))

Number of weekdays in 2022:
260


In [218]:
np.is_busday(np.datetime64('2022-06-05'))

np.False_

## Linear Algebra

In [222]:
matrix_a=np.random.randint(5,size=(2,3))
matrix_a

array([[1, 2, 3],
       [2, 3, 1]], dtype=int32)

In [223]:
matrix_b=np.random.randint(5,size=(3,2))
matrix_b

array([[2, 4],
       [3, 2],
       [3, 0]], dtype=int32)

In [224]:
np.matmul(matrix_a,matrix_b)

array([[17,  8],
       [16, 14]], dtype=int32)

In [227]:
matrix_c=np.matrix("0 1 2;1 0 3;4 -3 8")
matrix_c

matrix([[ 0,  1,  2],
        [ 1,  0,  3],
        [ 4, -3,  8]])

In [228]:
inverse = np.linalg.inv(matrix_c)
inverse

matrix([[-4.5,  7. , -1.5],
        [-2. ,  4. , -1. ],
        [ 1.5, -2. ,  0.5]])

In [229]:
# multipling inverse with original matrix will give indentify matrix
print(matrix_c*inverse)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
